<?php

namespace App\Model;





use App\Model;
use App\User;

class Question extends Model
{

    protected $with = [
        'replies'
    ];

    protected $guarded = [];



   public static function boot()
   {
       parent::boot(); // TODO: Change the autogenerated stub

       static::deleting(function ($q) {
           $q->replies->each->delete();
       });
   }

    public function user()
    {
       return $this->belongsTo(User::class);
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function getPathAttribute()
    {
        return ("api/question/$this->slug");
    }
}
