<?php

namespace App\Model;



use App\Model;
use App\User;

class Reply extends Model
{
   /* protected $with = [
        'likes'
    ];*/

   protected  $guarded = [];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        /*static::deleting(function ($r) {
            $r->likes->each->delete();
        });*/
    }

    public function question()
    {
        return $this->belongsTo(Question::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function like()
    {
        $this->hasMany(Like::class);
    }

    public function getReplyAttribute()
    {
        return $this->body;

    }
}
